<a href="https://colab.research.google.com/github/cowsilver57/sessac_test/blob/main/11%EC%9B%94_23%EC%9D%BC_(%EB%AA%A9)_Day_56.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1-D

##1-D Window

In [ ]:
import numpy as np
data = 10*np.arange(1,11)

L = len(data)
W = 3
print(data, '\n')

L_ = L - W + 1
for idx in range(L_):
    print(data[idx:idx+W])

##1-D Correlation

In [ ]:
import numpy as np

filter = np.array([-1, 1, -1])
data = np.array([-1, 0, -1, 0, 0, 1, -1, 1, -1, -1])

L = len(data)
W = len(filter)
L_ = L - W + 1 #8
result = []

for idx in range(L_):
    window = data[idx:idx+W]
    filtered_value = np.sum(window*filter)
    result.append(filtered_value)

print("Data:", data)
print("Filter:", filter)
print("Final Result:", result)

Data: [-1  0 -1  0  0  1 -1  1 -1 -1]
Filter: [-1  1 -1]
Final Result: [2, -1, 1, -1, 2, -3, 3, -1]


In [12]:
#for문 없이 구현하기
import numpy as np

filter = np.array([-1, 1, -1])
data = np.array([-1, 0, -1, 0, 0, 1, -1, 1, -1, -1])

L = len(data)
W = len(filter)
L_ = L - W + 1

index = np.arange(W) + np.arange(L_).reshape(-1, 1)

result = np.matmul(data[index], filter)

print("Data:", data)
print("Filter:", filter)
print("Final Result:", result)

Data: [-1  0 -1  0  0  1 -1  1 -1 -1]
Filter: [-1  1 -1]
Final Result: [ 2 -1  1 -1  2 -3  3 -1]


In [ ]:
#강사님 답
import numpy as np

np.random.seed(0)

data = np.random.randint(-1,2,(10,))
filter_ = np.array([-1, 1, -1])
print(f"{data=}")
print(f"{filter_=}")

L = len(data)
F = len(filter_)
L_ = L - F + 1
filtered = []

for idx in range(L_):
    window = data[idx:idx+F]
    filtered.append(np.dot(window, filter_))
    #window는 for문을 지나며 항상 바뀌는 부분
    #filter_는 항상 [-1,1,-1]로 일정
filtered = np.array(filtered)
print("filtering result:", filtered)

data=array([-1,  0, -1,  0,  0,  1, -1,  1, -1, -1])
filter_=array([-1,  1, -1])
filtering result: [ 2 -1  1 -1  2 -3  3 -1]


#2-D

##2-D Window

In [ ]:
import numpy as np

column = np.arange(1,8)
row = np.arange(5).reshape(-1, 1)
data = 10 * (row + column)

print(data)
print('-'*80)

L = len(row)*len(column) #35
W = 3

H_ = len(row) - W + 1 #3
W_ = len(column) - W + 1 #5

for row_idx in range(H_):
    for col_idx in range(W_):
        print(data[row_idx:row_idx+W, col_idx:col_idx+W],'\n')

##2-D Correlation

In [ ]:
import numpy as np

column = np.arange(1, 8)
row = np.arange(5).reshape(-1, 1)
data = 10 * (row + column)

filter = np.array([1, 2, 5, -10, 2, -2, 5, 1, -4]).reshape(3, 3)

L = len(row)*len(column) #35
W = 3

H_ = len(row) - W + 1 #3
W_ = len(column) - W + 1 #5

result = np.zeros((H_,W_))
print(result)

for row_idx in range(H_):
    for col_idx in range(W_):
        window = data[row_idx:row_idx+W, col_idx:col_idx+W]
        filtered_value = np.sum(window*filter)
        result[row_idx][col_idx] = filtered_value

print("Data\n:", data)
print("Filter:\n", filter)
print("Final Result:\n", result)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Data
: [[ 10  20  30  40  50  60  70]
 [ 20  30  40  50  60  70  80]
 [ 30  40  50  60  70  80  90]
 [ 40  50  60  70  80  90 100]
 [ 50  60  70  80  90 100 110]]
Filter:
 [[  1   2   5]
 [-10   2  -2]
 [  5   1  -4]]
Final Result:
 [[-30. -30. -30. -30. -30.]
 [-30. -30. -30. -30. -30.]
 [-30. -30. -30. -30. -30.]]


In [ ]:
#강사님 답
import numpy as np
data1 = 10*np.arange(1,8).reshape(1,-1)
data2 = 10*np.arange(5).reshape(-1,1)

data = data1+data2
filter_ = np.array([[1,2,5],
                   [-10,2,-2],
                   [5,1,-4]])
print(data, '\n')

H, W = data.shape
F = filter_.shape[0] #임시적으로 window size를 의미
H_ = H - F + 1
W_ = W - F + 1

filtered_data = np.zeros(shape=(H_, W_))
for h_idx in range(H_):
    for w_idx in range(W_):
        window = data[h_idx:h_idx+F,
                      w_idx:w_idx+F]
        z = np.sum(window*filter_)

        filtered_data[h_idx, w_idx] = z

print(filtered_data)

[[ 10  20  30  40  50  60  70]
 [ 20  30  40  50  60  70  80]
 [ 30  40  50  60  70  80  90]
 [ 40  50  60  70  80  90 100]
 [ 50  60  70  80  90 100 110]] 

[[-30. -30. -30. -30. -30.]
 [-30. -30. -30. -30. -30.]
 [-30. -30. -30. -30. -30.]]
