<a href="https://colab.research.google.com/github/cowsilver57/sessac_test/blob/main/1_Numpy(P1_24).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Objects in Python

Object = Data + Methods (데이터 + 방법)

In [8]:
#P4 Objects in Python
a = [1, 2, 3]
b = {'a':1, 'b':2, 'c':3}
c = (1, 2, 3)
print(type(a))
print(type(b))
print(type(c))

#P5,9 리스트의 함수
a = [1, 2, 3] #이 리스트에 적용할 수 있는 여러가지 함수를 출력
for attr in dir(a):
    print(attr)

#P6 튜플의 함수
# a = {'a':0, 'b':1, 'c':2}
# for attr in dir(a):
#     print(attr)

<class 'list'>
<class 'dict'>
<class 'tuple'>
__add__
__class__
__class_getitem__
__contains__
__delattr__
__delitem__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__iadd__
__imul__
__init__
__init_subclass__
__iter__
__le__
__len__
__lt__
__mul__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__reversed__
__rmul__
__setattr__
__setitem__
__sizeof__
__str__
__subclasshook__
append
clear
copy
count
extend
index
insert
pop
remove
reverse
sort
__class__
__class_getitem__
__contains__
__delattr__
__delitem__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__init__
__init_subclass__
__ior__
__iter__
__le__
__len__
__lt__
__ne__
__new__
__or__
__reduce__
__reduce_ex__
__repr__
__reversed__
__ror__
__setattr__
__setitem__
__sizeof__
__str__
__subclasshook__
clear
copy
fromkeys
get
items
keys
pop
popitem
setdefault
update
values


In [15]:
#P8 함수를 길게 풀어쓰는 법
a, b = 4, 2
print(a-b, a.__sub__(b))
print(a*b, a.__mul__(b))
print(a**b, a.__pow__(b))
print(a/b, a.__truediv__(b))
print(a//b, a.__floordiv__(b))
print(a%b, a.__mod__(b))
#앞의 결과와 뒤의 결과는 동일함.

2 2
8 8
16 16
2.0 2.0
2 2
0 0


In [18]:
#P10-11 Numpy의 함수
a = np.array([1,2,3])
print(type(a))
#다른 함수보다 더 많은 함수가 내장되어 있음.

<class 'numpy.ndarray'>


In [21]:
#P12-14 1겹 리스트 더하기의 여러가지 방법
u = [1,2,3]
v = [4,5,6]
#방법 1. 그냥 리스트를 붙이는 방법
w = u + v
print(w)

#각 리스트의 동일한 순서로 더하고 싶다면!
#방법 1. Python의 기본적인 방법
w = [0]*len(u)
for data_idx in range(len(u)):
    w[data_idx] = u[data_idx] + v[data_idx]
print(w)

#방법 2. numpy를 활용한 방법
u = np.array([1,2,3])
v = np.array([4,5,6])
print(u+v)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]
[5 7 9]


Numpy에 더 많은 함수가 내장되어 있고, 훨씬 짧은 식으로 구현 가능함.

In [25]:
#P15-17 2겹 리스트 더하기의 여러가지 방법
M = [[1,2,3],[4,5,6],[7,8,9]]
N = [[11,12,13],[14,15,16],[17,18,19]]

#방법 1.
n_row, n_col = len(M), len(M[0])
P = [[0]*n_col for _ in range(n_col)]
for row_idx in range(n_row):
    for col_idx in range(n_col):
        P[row_idx][col_idx] = M[row_idx][col_idx] + N[row_idx][col_idx]

for P_row in P :
    print(P_row)

#방법 2.
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
N = np.array([[11,12,13],
              [14,15,16],
              [17,18,19]])
print(M + N)

[12, 14, 16]
[18, 20, 22]
[24, 26, 28]
[[12 14 16]
 [18 20 22]
 [24 26 28]]


#Tensors and Ndarrays

(o,n,m) = (Matrix의 개수, 행, 열) = (Matrix, row, columns)

In [31]:
#여러 가지 차원 살펴보기
scalar_np = np.array(3.14)
vec_np = np.array([1,2,3])
mat_np = np.array([[1,2],[3,4]])
tensor_np = np.array([[[1,2,3],
                       [4,5,6]],

                      [[11,12,13],
                       [14,15,16]]])
print(scalar_np.shape)
print(vec_np.shape)
print(mat_np.shape)
print(tensor_np.shape)

print(len(()))
print(len((3,)))
print(len((2,2)))
print(len((2,2,3)))

()
(3,)
(2, 2)
(2, 2, 3)
0
1
2
3
