<a href="https://colab.research.google.com/github/cowsilver57/sessac_test/blob/main/3_Numpy(P43_55).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Changing ndarrays' shapes

In [13]:
#P43
a = np.arange(6)
b = np.reshape(a, (2,3))

print("원래 ndarray:", a)
print("바꾼 ndarray:\n", b,'\n')

#P44
c = np.arange(24)
d = np.reshape(c,(2,3,4))

print("원래 ndarray:", c)
print("바꾼 ndarray:\n", d, '\n')

#P45~46 -1 in np.reshape
a = np.arange(10)
b = a.reshape((2,-1))
c = a.reshape((5,-1))
print(a.shape)
print(b.shape)
print(c.shape)

원래 ndarray: [0 1 2 3 4 5]
바꾼 ndarray:
 [[0 1 2]
 [3 4 5]] 

원래 ndarray: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
바꾼 ndarray:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

(10,)
(2, 5)
(5, 2)


In [17]:
#P47
#0부터 10까지의 숫자를 (2,2) 모양으로 랜덤하게 구성
a = np.random.randint(0, 10, size=(2,2))
print(a, '\n')

row_vector = a.reshape(1,-1)
col_vector = a.reshape(-1,1)
print(row_vector.shape)
print(col_vector.shape)

[[9 0]
 [3 3]] 

(1, 4)
(4, 1)


In [23]:
#P48~50
#1부터 9까지의 숫자
M = np.arange(9)
#3,3 모양으로 배열
N = M.reshape((3,3))
#다시 펴기
O = N.flatten()

print(M, '\n')
print(N, '\n')
print(O, '\n')

A = np.arange(27)
B = A.reshape((3,3,3,))
B0, B1, B2 = B[0], B[1], B[2]
C = B.flatten()

print(A, '\n')
print(B, '\n')
print(C, '\n')

print("B0: \n", B0)
print("B1: \n", B1)
print("B2: \n", B2)

[0 1 2 3 4 5 6 7 8] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[0 1 2 3 4 5 6 7 8] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 

B0: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
B1: 
 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
B2: 
 [[18 19 20]
 [21 22 23]
 [24 25 26]]


#Element-wise Operations of ndarrays

In [24]:
#P51 Vector끼리의 합
a = np.random.randint(-5,5,(5,))
b = np.random.randint(-5,5,(5,))

print("a:", a)
print("b:", b)
print("a+b:", a + b)

a: [ 0 -3 -3  0  4]
b: [ 2  2 -1 -2  4]
a+b: [ 2 -1 -4 -2  8]


In [27]:
#P52, 54 Vector끼리의 사칙연산
a = np.random.randint(1,5,(5,))
b = np.random.randint(1,5,(5,))

print("a:", a)
print("b:", b)

print("a+b:", a+b, a.__add__(b))
print("a-b:", a-b, a.__sub__(b))
print("a*b:", a*b, a.__mul__(b))
print("a/b:", a/b, a.__truediv__(b))
print("a//b:", a//b, a.__floordiv__(b))
print("a%b:", a%b, a.__mod__(b))
print("a**b:", a**b, a.__pow__(b))

a: [1 1 4 1 1]
b: [1 3 1 2 1]
a+b: [2 4 5 3 2] [2 4 5 3 2]
a-b: [ 0 -2  3 -1  0] [ 0 -2  3 -1  0]
a*b: [1 3 4 2 1] [1 3 4 2 1]
a/b: [1.         0.33333333 4.         0.5        1.        ] [1.         0.33333333 4.         0.5        1.        ]
a//b: [1 0 4 0 1] [1 0 4 0 1]
a%b: [0 1 0 1 0] [0 1 0 1 0]
a**b: [1 1 4 1 1] [1 1 4 1 1]


In [28]:
#P53 Vector끼리의 참, 거짓 판단
a = np.random.randint(1,5,(5,))
b = np.random.randint(1,5,(5,))

print('a:', a)
print('b:', b, '\n')

print('a>b:', a>b)
print('a>=b:', a>=b)
print('a<b:', a<b)
print('a<=b:', a<=b)
print('a==b:', a==b)
print('a!=b:', a!=b)

a: [2 4 1 2 4]
b: [2 3 3 2 4] 

a>b: [False  True False False False]
a>=b: [ True  True False  True  True]
a<b: [False False  True False False]
a<=b: [ True False  True  True  True]
a==b: [ True False False  True  True]
a!=b: [False  True  True False False]


In [31]:
#P55 Matrix-matrix Case
M = np.random.randint(1,5,(2,3))
N = np.random.randint(1,5,(2,3))

print("M:\n",M, )
print("N:\n",N, '\n')

print("M+N:\n",M+N)
print("M-N:\n",M-N, '\n')

print("M>N:\n",M>N)
print("M>=N:\n",M>=N)

M:
 [[1 4 2]
 [4 4 2]]
N:
 [[3 3 2]
 [4 1 2]] 

M+N:
 [[4 7 4]
 [8 5 4]]
M-N:
 [[-2  1  0]
 [ 0  3  0]] 

M>N:
 [[False  True False]
 [False  True False]]
M>=N:
 [[False  True  True]
 [ True  True  True]]
