<a href="https://colab.research.google.com/github/cowsilver57/sessac_test/blob/main/4_Numpy(P56_79).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Broadcasting in NumPy

## 1. When ndims(number of dimensions;차원) are Equal

### 2차원

In [33]:
#P55-58
import numpy as np
A = np.arange(9).reshape(3,3)
B = 10*np.arange(3).reshape((-1,3))
C = A+B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(B.ndim, B.shape, B))
print("A+B: {}/{}\n{}".format(C.ndim, C.shape, C))

A: 2/(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
B: 2/(1, 3)
[[ 0 10 20]]
A+B: 2/(3, 3)
[[ 0 11 22]
 [ 3 14 25]
 [ 6 17 28]]


In [32]:
#P59-60
A = np.arange(9).reshape(3,3)
B =10*np.arange(3).reshape((3,-1))
C = A+B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(B.ndim, B.shape, B))
print("A+B: {}/{}\n{}".format(C.ndim, C.shape, C))

A: 2/(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
B: 2/(3, 1)
[[ 0]
 [10]
 [20]]
A+B: 2/(3, 3)
[[ 0  1  2]
 [13 14 15]
 [26 27 28]]


In [31]:
#P61-62
A = np.arange(3).reshape((3,-1))
B = 10*np.arange(3).reshape((-1,3))
C = A+B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(B.ndim, B.shape, B))
print("A+B: {}/{}\n{}".format(C.ndim, C.shape, C))

A: 2/(3, 1)
[[0]
 [1]
 [2]]
B: 2/(1, 3)
[[ 0 10 20]]
A+B: 2/(3, 3)
[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]]


### 3차원

In [30]:
#P63-64
A = np.arange(18).reshape((2,3,3))
B = 10*np.arange(9).reshape((1,3,3))
C = A+B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(B.ndim, B.shape, B))
print("A+B: {}/{}\n{}".format(C.ndim, C.shape, C))

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
B: 3/(1, 3, 3)
[[[ 0 10 20]
  [30 40 50]
  [60 70 80]]]
A+B: 3/(2, 3, 3)
[[[ 0 11 22]
  [33 44 55]
  [66 77 88]]

 [[ 9 20 31]
  [42 53 64]
  [75 86 97]]]


In [29]:
#P65-66
A = np.arange(18).reshape((2,3,3))
B = 10*np.arange(6).reshape((2,1,3))
C = A+B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(B.ndim, B.shape, B))
print("A+B: {}/{}\n{}".format(C.ndim, C.shape, C))

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
B: 3/(2, 1, 3)
[[[ 0 10 20]]

 [[30 40 50]]]
A+B: 3/(2, 3, 3)
[[[ 0 11 22]
  [ 3 14 25]
  [ 6 17 28]]

 [[39 50 61]
  [42 53 64]
  [45 56 67]]]


In [28]:
#P67-68
A = np.arange(18).reshape((2,3,3))
B = 10*np.arange(6).reshape((2,3,1))
C = A+B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(B.ndim, B.shape, B))
print("A+B: {}/{}\n{}".format(C.ndim, C.shape, C))

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
B: 3/(2, 3, 1)
[[[ 0]
  [10]
  [20]]

 [[30]
  [40]
  [50]]]
A+B: 3/(2, 3, 3)
[[[ 0  1  2]
  [13 14 15]
  [26 27 28]]

 [[39 40 41]
  [52 53 54]
  [65 66 67]]]


In [27]:
#P69-70
A = np.arange(6).reshape((2,1,3))
B = 10*np.arange(6).reshape((2,3,1))
C = A+B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(B.ndim, B.shape, B))
print("A+B: {}/{}\n{}".format(C.ndim, C.shape, C))

A: 3/(2, 1, 3)
[[[0 1 2]]

 [[3 4 5]]]
B: 3/(2, 3, 1)
[[[ 0]
  [10]
  [20]]

 [[30]
  [40]
  [50]]]
A+B: 3/(2, 3, 3)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[33 34 35]
  [43 44 45]
  [53 54 55]]]


## 2. When ndims are Not Equal

In [16]:
#P71 차원이 다른 두 배열의 곱
a = np.array(3)
u = np.arange(5)

print("shapes:{}/{}".format(a.shape, u.shape))
print("a:",a)
print("u:",u,'\n')
print("a*u:", a*u)

shapes:()/(5,)
a: 3
u: [0 1 2 3 4] 

a*u: [ 0  3  6  9 12]


In [22]:
#P72 차원이 다른 두 배열의 사칙연산과 크기 비교
a = np.array(3)
u = np.arange(1,5)

shapes = "shapes: {}/{}"
print(shapes.format(a.shape, u.shape))
print("a", a)
print("u", u, '\n')

print("a+u:", a+u)
print("a-u:", a-u)
print("a*u:", a*u)
print("a/u:", a/u)
print("a//u:", a//u)
print("a%u:", a%u)
print("a**u:", a**u, '\n')

print("a>u:", a>u)
print("a>=u:", a>=u)
print("a<u:", a<u)
print("a<=u:", a<=u)
print("a==u:", a==u)
print("a!=u:", a!=u)

shapes: ()/(4,)
a 3
u [1 2 3 4] 

a+u: [4 5 6 7]
a-u: [ 2  1  0 -1]
a*u: [ 3  6  9 12]
a/u: [3.   1.5  1.   0.75]
a//u: [3 1 1 0]
a%u: [0 1 0 3]
a**u: [ 3  9 27 81] 

a>u: [ True  True False False]
a>=u: [ True  True  True False]
a<u: [False False False  True]
a<=u: [False False  True  True]
a==u: [False False  True False]
a!=u: [ True  True False  True]


In [26]:
#P73-74
A = np.array([10,20])
B = np.arange(6).reshape((3,2))
C = A+B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(B.ndim, B.shape, B))
print("A+B: {}/{}\n{}".format(C.ndim, C.shape, C))

A: 1/(2,)
[10 20]
B: 2/(3, 2)
[[0 1]
 [2 3]
 [4 5]]
A+B: 2/(3, 2)
[[10 21]
 [12 23]
 [14 25]]


In [34]:
#P75-76
A = np.arange(24).reshape((2,3,4))
B = 10*np.arange(12).reshape(3,4)
C = A+B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(B.ndim, B.shape, B))
print("A+B: {}/{}\n{}".format(C.ndim, C.shape, C))

A: 3/(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B: 2/(3, 4)
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
A+B: 3/(2, 3, 4)
[[[  0  11  22  33]
  [ 44  55  66  77]
  [ 88  99 110 121]]

 [[ 12  23  34  45]
  [ 56  67  78  89]
  [100 111 122 133]]]


In [36]:
#P77-79
A = np.arange(24).reshape((2,3,4))
B = 10*np.arange(4).reshape(4,)
C = A+B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(B.ndim, B.shape, B))
print("A+B: {}/{}\n{}".format(C.ndim, C.shape, C))

A: 3/(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B: 1/(4,)
[ 0 10 20 30]
A+B: 3/(2, 3, 4)
[[[ 0 11 22 33]
  [ 4 15 26 37]
  [ 8 19 30 41]]

 [[12 23 34 45]
  [16 27 38 49]
  [20 31 42 53]]]
