<a href="https://colab.research.google.com/github/cowsilver57/sessac_test/blob/main/5_Numpy(P80_92).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Basic Indexing and Slicing

In [ ]:
#P80
import numpy as np
a = np.arange(10)
print(f"ndarry: \n{a}\n")

print("a[0]:", a[0])
print("a[2]:", a[2])

print("a[-1]:", a[-1])
print("a[-2]:", a[-2], '\n')

print('-'*80)

#P81 [start:end]
b = np.arange(10)
print(f"ndarray: \n{b}\n")

print("b[0:3]:", b[0:3])
print("b[3:7]:", b[3:7])
print("b[5:-1]:", b[5:-1])

ndarry: 
[0 1 2 3 4 5 6 7 8 9]

a[0]: 0
a[2]: 2
a[-1]: 9
a[-2]: 8 

--------------------------------------------------------------------------------
ndarray: 
[0 1 2 3 4 5 6 7 8 9]

b[0:3]: [0 1 2]
b[3:7]: [3 4 5 6]
b[5:-1]: [5 6 7 8]


In [16]:
#P82
a = np.arange(10)
print(f"ndarray: \n{a}\n")

print("a[2:]", a[2:])
print("a[-2:]", a[-2:])
print("a[:5]", a[:5])
print("a[-3]", a[:-3])
print("a[:]", a[:])

print('-'*80)
#P83-84 [start:end:step]
b = np.arange(10)
print(f"ndarray: \n{b}\n")
print("b[2:7:2]", b[2:7:2])
print("b[::3]", b[::3])

c = np.arange(10)
print(f"ndarray: \n{c}\n")
print("c[7:2:-1]", c[7:2:-1])
print("c[::-1]", c[::-1])
print("c[8:3:-2]", c[8:3:-2])
print("c[::-3]", c[::-3])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[2:] [2 3 4 5 6 7 8 9]
a[-2:] [8 9]
a[:5] [0 1 2 3 4]
a[-3] [0 1 2 3 4 5 6]
a[:] [0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------------------------------------
ndarray: 
[0 1 2 3 4 5 6 7 8 9]

b[2:7:2] [2 4 6]
b[::3] [0 3 6 9]
ndarray: 
[0 1 2 3 4 5 6 7 8 9]

c[7:2:-1] [7 6 5 4 3]
c[::-1] [9 8 7 6 5 4 3 2 1 0]
c[8:3:-2] [8 6 4]
c[::-3] [9 6 3 0]


In [23]:
#P85 출력 순서
a = [[0,1,2],[3,4,5],[6,7,8]]
print(a[0])
print(a[1])
print(a[2])

print(a[0][0], a[0][1], a[0][2])
print(a[1][0], a[1][1], a[1][2])
print(a[2][0], a[2][1], a[2][2])
print('-'*80)

#P86
b = np.arange(12).reshape((3,4))
print(f"ndarray:\n{b}\n")
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])

[0, 1, 2]
[3, 4, 5]
[6, 7, 8]
0 1 2
3 4 5
6 7 8
--------------------------------------------------------------------------------
ndarray:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a[0]: [0, 1, 2]
a[1]: [3, 4, 5]
a[2]: [6, 7, 8]


In [32]:
#P87 Numpy이 방법이 더 편하다는 것을 알려줌~
a = np.arange(9).reshape((3,3))
print(f"ndarray a:\n{a}\n")
print(a[0,0], a[0,1], a[0,2])
print(a[1,0], a[1,1], a[1,2])
print(a[2,0], a[2,1], a[2,2])
print('-'*80)

#P88
b = np.arange(12).reshape((3,4))
print(f"ndarray b:\n{b}\n")
print("b[0,1:]:", b[0,1:])
print("b[1,:3]:", b[1,:3])
print("b[2,1:3]:", b[2,1:3])
print('-'*80)

#P89
c = np.arange(12).reshape((4,3))
print(f"ndarray c:\n{c}\n")
print("c[1:,0]:", c[1:,0])
print("c[:3,1]:", c[:3,1])
print("c[1:3,2]:", c[1:3,2])

ndarray a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

0 1 2
3 4 5
6 7 8
--------------------------------------------------------------------------------
ndarray b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

b[0,1:]: [1 2 3]
b[1,:3]: [4 5 6]
b[2,1:3]: [ 9 10]
--------------------------------------------------------------------------------
ndarray c:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

c[1:,0]: [3 6 9]
c[:3,1]: [1 4 7]
c[1:3,2]: [5 8]


In [39]:
#P90 연습문제
import numpy as np
a = np.arange(3*3*3).reshape((3,3,3))
print(f"ndarray a: \n{a}\n")
print('-'*80)

#P91
#각 분단의 2열까지만 뽑기
print("a[:,:2,:]:\n", a[:, :2, :])
print('-'*80)

#P92
#2번째 분단에서 2열부터 뒤에서 2개씩만 뽑기
print("a[1:,-2:,-2:]:\n", a[1:, -2:, -2:])
print('-'*80)

ndarray a: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

--------------------------------------------------------------------------------
a[:,:2,:]:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 9 10 11]
  [12 13 14]]

 [[18 19 20]
  [21 22 23]]]
--------------------------------------------------------------------------------
a[1:,-2:,-2:]:
 [[[13 14]
  [16 17]]

 [[22 23]
  [25 26]]]
--------------------------------------------------------------------------------
