<a href="https://colab.research.google.com/github/cowsilver57/sessac_test/blob/main/Chapter2_Scikit_learn(4%2C5%EC%9D%BC%EC%B0%A8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Scikit-learn

In [ ]:
import sklearn
print(sklearn.__version__)

1.2.2


## 프레임워크 익히기



*   fit 함수 : 머신러닝 모델 학습
*   predict 함수 : 학습된 모델의 예측



*   분류 알고리즘 : classification
*   회귀 알고리즘 : regression





## scikit-learn 내장 데이터 세트

In [ ]:
#그 중 iris data 불러오기
from sklearn.datasets import load_iris

iris = load_iris()
print("붓꽃 데이터세트 타입:", type(iris))

keys = iris.keys()
print("붓꽃 데이터세트 키:", keys)

print('feature_names:', iris.feature_names)
print('\ntarget_names:', iris.target_names)
#print('\ndata:', iris.data)
#print('\ntarget:', iris.target)

붓꽃 데이터세트 타입: <class 'sklearn.utils._bunch.Bunch'>
붓꽃 데이터세트 키: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
feature_names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

target_names: ['setosa' 'versicolor' 'virginica']


##scikit-learn 머신러닝 만들어보기

In [ ]:
#iris_data 훑어보기
import pandas as pd
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
print(iris_df.head(3))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0  


In [ ]:
#학습용 데이터와 테스트 데이터 분리하기
from sklearn.model_selection import train_test_split

iris_data = iris.data
iris_label = iris.target

x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state = 11)

print('train dataset')
print('x_train dataset:', len(x_train))
print('y_train dataset:', len(y_train))
print('\ntest dataset')
print('x_test dataset:', len(x_test))
print('y_test dataset:', len(y_test))

train dataset
x_train dataset: 120
y_train dataset: 120

test dataset
x_test dataset: 30
y_test dataset: 30


In [ ]:
#의사결정 트리 머신러닝 학습
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(x_train, y_train)

#의사결정 트리 머신러닝 테스트/평가
from sklearn.metrics import accuracy_score
pred = dt_clf.predict(x_test)
ac_score = accuracy_score(y_test, pred)
print("예측 정확도:", ac_score)

예측 정확도: 0.9333333333333333


##scikit-learn 머신러닝 만드는 순서


1.   데이터 세트 분리: 데이터 세트를 학습, 테스트 데이터로 분리함.
2.   예측 수행: 학습 데이터를 기반으로 머신러닝 알고리즘을 적용해 모델을 학습시킴.
3.   예측 수행: 학습된 머신러닝 모델을 이용해 테스트 데이터 분류를 예측함.
4.   평가: 예측된 결괏값과 데스트 데이터의 실제 결괏값을 비교해 머신러닝 모델의 성능을 평가함.



##scikit-learn 데이터 전처리






###1.결측치 허용 x

고정된 다른 상수로 변환해야함. 만약 변환이 어렵다면 값을 삭제하는 것이 좋음.

###2.문자열 값 허용 x

인코딩을 통해 숫자형으로 변환해야함. 텍스트형 변수는 변환이 어렵기 때문에 삭제하는 것이 좋음. (인코딩의 종류는 레이블 인코딩, 원-핫 인코딩, 스케일링임.)

####2-1. 레이블 인코딩

명목형 변수를 코드형 숫자 값으로 변환하는 것

In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자레인지','컴퓨터','TV','냉장고','컴퓨터','컴퓨터']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

print('인코딩 반환값:', labels)
print('인코딩 클래스:', encoder.classes_)

#위의 경우는 데이터가 적어 직관적으로 알 수 있지만 데이터가 많다면 이것이 불가함.
#inverse_transform 함수를 활용해 속성값만 파악할 수 있음.

origins = encoder.inverse_transform([0,1,2,3,0,1,3,3])
print('디코딩 원본값:', origins)

인코딩 반환값: [0 1 2 3 0 1 3 3]
인코딩 클래스: ['TV' '냉장고' '전자레인지' '컴퓨터']
디코딩 원본값: ['TV' '냉장고' '전자레인지' '컴퓨터' 'TV' '냉장고' '컴퓨터' '컴퓨터']


####2-2. 원-핫 인코딩

변수 값의 유형에 따라 새로운 변수를 추가해 고윳값에 해당하는 컬럼에만 1을 표시하고 나머지 컬럼에는 0을 표시하는 방법(레이블 인코딩의 단점 보완)

*   주의할 점
1. OneHotEncoder로 변환하기 전에 모든 문자열 값이 숫자형 값으로 변환되어야 함.
2. 입력 값으로 2차원 데이터가 필요함.



In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

#입력 값을 2차원 데이터로 변환
labels = labels.reshape(-1,1)


oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원=핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
원=핫 인코딩 데이터 차원
(8, 4)


####2-3. get_dummies(pandas)



* pandas에는 원-핫 인코딩을 더 쉽게 지원하는 함수 존재함.
* get_dummies 함수를 활용하면 명복형 데이터를 숫자형으로 변환할 필요 X
* 바로 2차원 데이터로 변환하여 인코딩 수행함.





In [ ]:
import pandas as pd

item_df = pd.DataFrame({'item':items})
pd.get_dummies(item_df)

item_TV  item_냉장고  item_전자레인지  item_컴퓨터
0        1         0           0         0
1        0         1           0         0
2        0         0           1         0
3        0         0           0         1
4        1         0           0         0
5        0         1           0         0
6        0         0           0         1
7        0         0           0         1

####2-4. 스케일링

* 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업
* 2가지 방법이 있음.-> 표준화, 정규화

In [ ]:
#스케일링 데이터 세트 훑어보기
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature들의 평균 값:\n', iris_df.mean())
print('feature들의 분산 값:\n', iris_df.var())

feature들의 평균 값:
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
feature들의 분산 값:
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [ ]:
#각 변수를 표준화해서 변환
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature들의 평균 값:\n', iris_df_scaled.mean())
print('feature들의 분산 값:\n', iris_df_scaled.var())

#결론으로 평균은 0, 분산은 1에 가까워짐을 알 수 있다.

feature들의 평균 값:
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature들의 분산 값:
 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [ ]:
#각 변수를 최대-최소 정규화 ; 데이터 값을 0과 1 사이의 범위 값으로 변환함.
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature들의 최소 값:\n', iris_df_scaled.min())
print('feature들의 최대 값:\n', iris_df_scaled.max())

feature들의 최소 값:
 sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature들의 최대 값:
 sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [ ]:
#스케일링 주의사항
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터:', np.round(train_array.reshape(-1),2))
print('Scaled train_array 데이터:', np.round(train_scaled.reshape(-1),2))

#scaler.fit(test_array)
test_scaled = scaler.transform(train_array)

print('\n원본 test_array 데이터:', np.round(test_array.reshape(-1),2))
print('\n원본 test_array 데이터:', np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터: [0 1 2 3 4 5]

원본 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
